#!/usr/bin/env python3
"""
CulinaryVLM — Stage 9B: Fill QA Answers
════════════════════════════════════════════

Fills in empty answers for Medium, Hard, and Expert tier QA pairs
generated by Stage 9.  Uses local Ollama (qwen2.5:32b-instruct) with
tier-specific system prompts.

For Expert tier, canonical recipe metadata is loaded from
configs/canonical_recipes/{category}.json to ground the answers.

Usage:
    python pipeline/09b_fill_qa_answers.py --tier medium
    python pipeline/09b_fill_qa_answers.py --tier hard   --model qwen2.5:32b-instruct
    python pipeline/09b_fill_qa_answers.py --tier expert --model qwen2.5:32b-instruct
    python pipeline/09b_fill_qa_answers.py --tier medium --limit 50

Input:  datasets/qa/train.json, datasets/qa/test.json
Output: datasets/qa/train.json, datasets/qa/test.json (updated in-place)
"""

from __future__ import annotations

import argparse, json, logging, os, sys, time
from pathlib import Path
from typing import Any

import yaml
from dotenv import load_dotenv

load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(asctime)s │ %(levelname)-7s │ %(message)s", datefmt="%H:%M:%S")
logger = logging.getLogger("stage_9b")
PROJECT_ROOT = Path(__file__).resolve().parent.parent

sys.path.insert(0, str(PROJECT_ROOT))
from pipeline.utils.ollama_client import check_ollama, ollama_chat  # noqa: E402

CHECKPOINT_EVERY = 50

# ─── Tier-specific system prompts ─────────────────────────────

SYSTEM_PROMPTS = {
    "medium": (
        "You are a culinary expert specializing in Indian biryani preparation. "
        "Answer the question about a specific biryani cooking process shown in a video. "
        "Give a detailed, accurate answer in 3-5 sentences. "
        "Focus on the specific cooking technique, ingredients, and visual elements."
    ),
    "hard": (
        "You are a culinary expert specializing in regional Indian biryani variations. "
        "Answer the comparison question about different biryani styles. "
        "Give a detailed, analytical answer in 4-6 sentences. "
        "Highlight key differences in technique, ingredients, and presentation."
    ),
    "expert": (
        "You are a food scientist and culinary expert with deep knowledge of Indian cooking chemistry, "
        "regional food traditions, and biryani preparation science. "
        "Answer the expert-level question with scientific precision and culinary insight in 5-8 sentences. "
        "Reference specific chemical reactions, physical processes, or cultural traditions where relevant."
    ),
}


def load_canonical_recipes() -> dict[str, dict]:
    """Load all canonical recipes for grounding expert answers."""
    recipe_dir = PROJECT_ROOT / "configs" / "canonical_recipes"
    recipes: dict[str, dict] = {}
    if not recipe_dir.exists():
        return recipes

    for fp in recipe_dir.glob("*.json"):
        try:
            with open(fp) as f:
                r = json.load(f)
            cat = r.get("category", fp.stem.replace("_", " ").title())
            recipes[cat] = r
        except (json.JSONDecodeError, OSError):
            pass

    logger.info(f"Loaded {len(recipes)} canonical recipes for grounding")
    return recipes


def _build_expert_context(qa: dict, recipes: dict[str, dict]) -> str:
    """Build grounding context for expert-tier questions using canonical recipes."""
    category = qa.get("category", "")
    # Handle cross-category format like "Hyderabadi_vs_Kolkata"
    cats = [c.strip() for c in category.replace("_vs_", ",").split(",")]

    context_parts = []
    for cat in cats:
        recipe = recipes.get(cat, {})
        if recipe:
            context_parts.append(
                f"=== {cat} Biryani ===\n"
                f"Region: {recipe.get('region', 'N/A')}\n"
                f"Dum method: {recipe.get('dum_method', 'N/A')}\n"
                f"Spice intensity: {recipe.get('spice_intensity', 'N/A')}\n"
                f"Key spices: {', '.join(recipe.get('key_spices', []))}\n"
                f"Rice: {recipe.get('rice_type', 'N/A')}\n"
                f"Vessel: {recipe.get('cooking_vessel', 'N/A')}\n"
                f"Marination: {recipe.get('marination_strategy', 'N/A')}\n"
                f"Features: {'; '.join(recipe.get('distinguishing_features', []))}\n"
            )

    if context_parts:
        return "Reference recipe data:\n\n" + "\n".join(context_parts)
    return ""


def fill_answers(
    qa_pairs: list[dict],
    tier: str,
    host: str,
    model: str,
    recipes: dict[str, dict],
    limit: int | None = None,
) -> int:
    """Fill empty answers for the specified tier. Returns count of answers filled."""
    system_prompt = SYSTEM_PROMPTS.get(tier, SYSTEM_PROMPTS["medium"])
    filled = 0

    # Filter to only entries needing generation
    targets = [
        (i, qa) for i, qa in enumerate(qa_pairs)
        if qa.get("tier") == tier and qa.get("needs_generation", False)
    ]

    if limit:
        targets = targets[:limit]

    logger.info(f"  {tier.upper()}: {len(targets)} entries to fill")

    for idx, (orig_idx, qa) in enumerate(targets):
        question = qa.get("question", "")
        if not question:
            continue

        # Build user prompt — add grounding context for expert tier
        if tier == "expert":
            context = _build_expert_context(qa, recipes)
            user_prompt = f"{context}\n\nQuestion: {question}" if context else f"Question: {question}"
        else:
            user_prompt = f"Question: {question}"

        try:
            answer = ollama_chat(
                host=host,
                model=model,
                system=system_prompt,
                user=user_prompt,
                num_predict=1024,
                temperature=0.3,
                json_format=False,
            )

            if answer:
                qa_pairs[orig_idx]["answer"] = answer
                qa_pairs[orig_idx]["needs_generation"] = False
                filled += 1
            else:
                logger.warning(f"  Empty answer for Q: {question[:60]}...")

        except Exception as e:
            logger.warning(f"  Error filling answer: {e}")

        if (idx + 1) % 20 == 0:
            logger.info(f"  Progress: {idx+1}/{len(targets)} ({filled} filled)")

        # Yield for checkpointing
        if (idx + 1) % CHECKPOINT_EVERY == 0:
            yield filled  # Signal checkpoint needed

    return filled


def main() -> None:
    parser = argparse.ArgumentParser(description="CulinaryVLM Stage 9B — Fill QA Answers")
    parser.add_argument("--tier", required=True, choices=["medium", "hard", "expert"],
                        help="Which tier to fill answers for")
    parser.add_argument("--config", default="configs/config.yaml")
    parser.add_argument("--limit", type=int, default=None,
                        help="Max number of answers to generate")
    parser.add_argument("--host", default="http://localhost:11434",
                        help="Ollama server URL (default: http://localhost:11434)")
    parser.add_argument("--model", default="qwen2.5:32b-instruct",
                        help="Ollama model name (default: qwen2.5:32b-instruct)")
    args = parser.parse_args()

    logger.info("╔══════════════════════════════════════════════════╗")
    logger.info("║  CulinaryVLM — Stage 9B: Fill QA Answers        ║")
    logger.info("╚══════════════════════════════════════════════════╝")
    logger.info(f"Tier: {args.tier}, Model: {args.model}")

    # Validate Ollama
    check_ollama(args.host, args.model)

    qa_dir = PROJECT_ROOT / "datasets" / "qa"
    train_path = qa_dir / "train.json"
    test_path = qa_dir / "test.json"

    if not train_path.exists() or not test_path.exists():
        logger.error("train.json or test.json not found. Run Stage 9 first.")
        sys.exit(1)

    # Load canonical recipes for expert grounding
    recipes = load_canonical_recipes() if args.tier == "expert" else {}

    # Process both train and test splits
    total_filled = 0
    for split_name, split_path in [("train", train_path), ("test", test_path)]:
        logger.info(f"\nProcessing {split_name} split...")

        with open(split_path) as f:
            data = json.load(f)

        qa_pairs = data.get("qa_pairs", [])
        tier_count = sum(1 for qa in qa_pairs if qa.get("tier") == args.tier and qa.get("needs_generation", False))

        if tier_count == 0:
            logger.info(f"  No {args.tier} entries needing generation in {split_name}")
            continue

        logger.info(f"  Found {tier_count} {args.tier} entries in {split_name}")

        # Fill answers with checkpointing
        system_prompt = SYSTEM_PROMPTS.get(args.tier, SYSTEM_PROMPTS["medium"])
        targets = [
            (i, qa) for i, qa in enumerate(qa_pairs)
            if qa.get("tier") == args.tier and qa.get("needs_generation", False)
        ]

        if args.limit:
            targets = targets[:args.limit]

        filled = 0
        for idx, (orig_idx, qa) in enumerate(targets):
            question = qa.get("question", "")
            if not question:
                continue

            # Build user prompt
            if args.tier == "expert":
                context = _build_expert_context(qa, recipes)
                user_prompt = f"{context}\n\nQuestion: {question}" if context else f"Question: {question}"
            else:
                user_prompt = f"Question: {question}"

            try:
                answer = ollama_chat(
                    host=args.host,
                    model=args.model,
                    system=system_prompt,
                    user=user_prompt,
                    num_predict=1024,
                    temperature=0.3,
                    json_format=False,
                )

                if answer:
                    qa_pairs[orig_idx]["answer"] = answer
                    qa_pairs[orig_idx]["needs_generation"] = False
                    filled += 1
                else:
                    logger.warning(f"  Empty answer for Q: {question[:60]}...")

            except Exception as e:
                logger.warning(f"  Error filling answer: {e}")

            if (idx + 1) % 20 == 0:
                logger.info(f"  Progress: {idx+1}/{len(targets)} ({filled} filled)")

            # Checkpoint
            if (idx + 1) % CHECKPOINT_EVERY == 0:
                data["qa_pairs"] = qa_pairs
                with open(split_path, "w") as f:
                    json.dump(data, f, indent=2)
                logger.info(f"  Checkpoint saved: {split_name} ({filled} filled so far)")

        # Final save for this split
        data["qa_pairs"] = qa_pairs
        with open(split_path, "w") as f:
            json.dump(data, f, indent=2)

        total_filled += filled
        logger.info(f"  {split_name}: filled {filled}/{len(targets)} answers")

    logger.info(f"\n{'═'*50}")
    logger.info(f"FILL QA ANSWERS ({args.tier}): {total_filled} answers generated")
    logger.info(f"{'═'*50}")
    logger.info("✓ Stage 9B complete!")


if __name__ == "__main__":
    main()
